### ISSUE TITLE
Element not defined

### ISSUE THREAD

**Issue by Bashamega** [editor-js/awesome-editorjs#90]
Hello:)
I have built a nextjs website using the awesome editors libraries, but there is an error occurring while deploying, I think it is originated from one of the editorjs lib.
I hope you can fix it. I really like the lib
error:
```
[11:17:03.861] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[11:17:03.974] Cloning github.com/Bashamega/webdesignertool (Branch: main, Commit: 84c549b)
[11:17:03.983] Skipping build cache, deployment was triggered without cache.
[11:17:05.051] Cloning completed: 1.077s
[11:17:05.474] Running "vercel build"
[11:17:06.337] Vercel CLI 32.1.0
[11:17:06.593] Installing dependencies...
[11:17:14.727] 
[11:17:14.728] added 227 packages in 8s
[11:17:14.728] 
[11:17:14.728] 30 packages are looking for funding
[11:17:14.728]   run `npm fund` for details
[11:17:14.747] Detected Next.js version: 13.4.19
[11:17:14.749] Detected `package-lock.json` generated by npm 7+...
[11:17:14.749] Running "npm run build"
[11:17:15.163] 
[11:17:15.163] > webdesigner@0.1.0 build
[11:17:15.163] > next build
[11:17:15.163] 
[11:17:15.680] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[11:17:15.680] This information is used to shape Next.js' roadmap and prioritize features.
[11:17:15.680] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[11:17:15.680] https://nextjs.org/telemetry
[11:17:15.681] 
[11:17:15.769] - info Creating an optimized production build...
[11:17:27.801] - info Compiled successfully
[11:17:27.802] - info Linting and checking validity of types...
[11:17:27.983] - info Collecting page data...
[11:17:38.364] - info Generating static pages (0/4)
[11:17:38.484] - info Generating static pages (1/4)
[11:17:38.556] ReferenceError: Element is not defined
[11:17:38.556]     at /vercel/path0/.next/server/chunks/767.js:45:381
[11:17:38.556]     at /vercel/path0/.next/server/chunks/767.js:45:38
[11:17:38.556]     at 9168 (/vercel/path0/.next/server/chunks/767.js:45:45)
[11:17:38.556]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[11:17:38.556]     at 3404 (/vercel/path0/.next/server/app/page.js:326:76)
[11:17:38.556]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[11:17:38.556]     at M (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:24:46)
[11:17:38.556]     at ma (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:28:324)
[11:17:38.557]     at Object.<anonymous> (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:31:63)
[11:17:38.557]     at JSON.parse (<anonymous>)
[11:17:38.598] 
[11:17:38.598] Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[11:17:38.598] ReferenceError: Element is not defined
[11:17:38.598]     at /vercel/path0/.next/server/chunks/767.js:45:381
[11:17:38.599]     at /vercel/path0/.next/server/chunks/767.js:45:38
[11:17:38.599]     at 9168 (/vercel/path0/.next/server/chunks/767.js:45:45)
[11:17:38.599]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[11:17:38.599]     at 3404 (/vercel/path0/.next/server/app/page.js:326:76)
[11:17:38.599]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[11:17:38.599]     at M (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:24:46)
[11:17:38.599]     at ma (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:28:324)
[11:17:38.599]     at Object.<anonymous> (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:31:63)
[11:17:38.599]     at JSON.parse (<anonymous>)
[11:17:38.599] - info Generating static pages (2/4)
[11:17:38.644] - info Generating static pages (3/4)
[11:17:38.676] - info Generating static pages (4/4)
[11:17:38.678] 
[11:17:38.678] > Export encountered errors on following paths:
[11:17:38.678] 	/page: /
[11:17:38.722] Error: Command "npm run build" exited with 1
```
This is the link for the source code: [https://github.com/Bashamega/webdesignertool](https://github.com/Bashamega/webdesignertool)

**Comment by talyguryn** [comment]
Hey, thanks for the question, but you're unlikely to get a solution in this repository.

Please use Editor.js repository [codex-team/editor.js](codex-team/editor.js) for questions about the editor. The developers or the community will definitely help you!
